In [1]:
import pandas as pd

In [2]:
import pandas as pd

customers = pd.read_csv("../data/dim_customers.csv")
products = pd.read_csv("../data/dim_products.csv")
targets = pd.read_csv("../data/dim_targets_orders.csv")

order_line = pd.read_csv("../data/fact_order_line.csv")
aggregate = pd.read_csv("../data/fact_aggregate.csv")

In [3]:
customers.head()

   customer_id     customer_name            city currency
0       789101  Costco Wholesale  New Jersey, US      USD
1       789102      Vijay Stores       Ahmedabad      INR
2       789103      Vijay Stores        Vadodara      INR
3       789121          Coolblue       Ahmedabad      INR
4       789122          Coolblue        Vadodara      INR

In [4]:
products.head()

    product_name  product_id category  price_INR  price_USD
0    AM Milk 500    25891101    Dairy        125        4.0
1    AM Milk 250    25891102    Dairy         62        2.0
2    AM Milk 100    25891103    Dairy         25        1.0
3  AM Butter 100    25891201    Dairy         60        2.0
4  AM Butter 250    25891202    Dairy        150        4.0

In [5]:
targets.head()

   customer_id  ontime_target%  infull_target%  otif_target%
0       789201              87              81            70
1       789202              85              81            69
2       789203              92              76            70
3       789301              89              78            69
4       789303              88              78            69

In [6]:
order_line.head()

,order_id,order_placement_date,customer_id,product_id,order_qty,agreed_delivery_date,actual_delivery_date,delivery_qty,In Full,On Time,On Time In Full
0,FMR34203601,01-03-2025,789203,25891601,110,04-03-2025,04-03-2025,110,1,1,1
1,FMR32320302,01-03-2025,789320,25891203,347,02-03-2025,02-03-2025,347,1,1,1
2,FMR33320501,01-03-2025,789320,25891203,187,03-03-2025,03-03-2025,150,0,1,0
3,FMR34220601,01-03-2025,789220,25891203,235,04-03-2025,04-03-2025,235,1,1,1
4,FMR33703603,01-03-2025,789703,25891203,176,03-03-2025,03-03-2025,176,1,1,1

In [7]:
aggregate.head()

      order_id  customer_id order_placement_date  on_time  in_full  otif
0  FMR32103503       789103           01-03-2025        1        0     0
1  FMR34103403       789103           01-03-2025        1        0     0
2  FMR32103602       789103           01-03-2025        1        0     0
3  FMR33103602       789103           01-03-2025        1        0     0
4  FMR33103401       789103           01-03-2025        1        0     0

In [8]:
customers.info()
products.info()
targets.info()
order_line.info()
aggregate.info()

<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    35 non-null     int64
 1   customer_name  35 non-null     str
 2   city           35 non-null     str
 3   currency       35 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_name  18 non-null     str
 1   product_id    18 non-null     int64
 2   category      18 non-null     str
 3   price_INR     18 non-null     int64
 4   price_USD     18 non-null     float64
dtypes: float64(1), int64(2), str(2)
memory usage: 852.0 bytes
<class 'pandas.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     35 non-null     int64
 1   ontime_target%  35 non-null     int64
 2   infull_target%  35 non-null     int64
 3   otif_target%    35 non-null     int64
dtypes: int64(4)
memory usage: 1.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 24195 entries, 0 to 24194
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              24195 non-null  str
 1   order_placement_date  24195 non-null  str
 2   customer_id           24195 non-null  int64
 3   product_id            24195 non-null  int64
 4   order_qty             24195 non-null  int64
 5   agreed_delivery_date  24195 non-null  str
 6   actual_delivery_date  24195 non-null  str
 7   delivery_qty          24195 non-null  int64
 8   In Full               24195 non-null  int64
 9   On Time               24195 non-null  int64
 10  On Time In Full       24195 non-null  int64
dtypes: int64(7), str(4)
memory usage: 2.0 MB
<class 'pandas.DataFrame'>
RangeIndex: 13467 entries, 0 to 13466
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_id              13467 non-null  str
 1   customer_id           13467 non-null  int64
 2   order_placement_date  13467 non-null  str
 3   on_time               13467 non-null  int64
 4   in_full               13467 non-null  int64
 5   otif                  13467 non-null  int64
dtypes: int64(4), str(2)
memory usage: 631.4 KB

In [9]:
customers.shape

(35, 4)

In [10]:
products.shape

(18, 5)

In [11]:
order_line.shape

(24195, 11)

In [12]:
aggregate.shape

(13467, 6)

In [13]:
targets.shape

(35, 4)

In [14]:
print(customers.shape)

print(products.shape)

print(order_line.shape)

print(aggregate.shape)

print(targets.shape)

(35, 4)
(18, 5)
(24195, 11)
(13467, 6)
(35, 4)

In [15]:
print(customers.columns.tolist())

print(products.columns.tolist())

print(order_line.columns.tolist())

print(aggregate.columns.tolist())

print(targets.columns.tolist())

['customer_id', 'customer_name', 'city', 'currency']
['product_name', 'product_id', 'category', 'price_INR', 'price_USD']
['order_id', 'order_placement_date', 'customer_id', 'product_id', 'order_qty', 'agreed_delivery_date', 'actual_delivery_date', 'delivery_qty', 'In Full', 'On Time', 'On Time In Full']
['order_id', 'customer_id', 'order_placement_date', 'on_time', 'in_full', 'otif']
['customer_id', 'ontime_target%', 'infull_target%', 'otif_target%']

In [16]:
print(customers.isnull().sum())

print(products.isnull().sum())

print(order_line.isnull().sum())

print(aggregate.isnull().sum())

print(targets.isnull().sum())

customer_id      0
customer_name    0
city             0
currency         0
dtype: int64
product_name    0
product_id      0
category        0
price_INR       0
price_USD       0
dtype: int64
order_id                0
order_placement_date    0
customer_id             0
product_id              0
order_qty               0
agreed_delivery_date    0
actual_delivery_date    0
delivery_qty            0
In Full                 0
On Time                 0
On Time In Full         0
dtype: int64
order_id                0
customer_id             0
order_placement_date    0
on_time                 0
in_full                 0
otif                    0
dtype: int64
customer_id       0
ontime_target%    0
infull_target%    0
otif_target%      0
dtype: int64

In [17]:
print(customers.duplicated().sum())

print(products.duplicated().sum())

print(order_line.duplicated().sum())

print(aggregate.duplicated().sum())

print(targets.duplicated().sum())

0
0
0
0
0

In [18]:
print(customers.dtypes)

print(products.dtypes)

print(order_line.dtypes)

print(aggregate.dtypes)

print(targets.dtypes)

customer_id      int64
customer_name      str
city               str
currency           str
dtype: object
product_name        str
product_id        int64
category            str
price_INR         int64
price_USD       float64
dtype: object
order_id                  str
order_placement_date      str
customer_id             int64
product_id              int64
order_qty               int64
agreed_delivery_date      str
actual_delivery_date      str
delivery_qty            int64
In Full                 int64
On Time                 int64
On Time In Full         int64
dtype: object
order_id                  str
customer_id             int64
order_placement_date      str
on_time                 int64
in_full                 int64
otif                    int64
dtype: object
customer_id       int64
ontime_target%    int64
infull_target%    int64
otif_target%      int64
dtype: object

In [19]:
order_line["order_placement_date"] = pd.to_datetime(
    order_line["order_placement_date"],
    dayfirst=True
)

order_line["agreed_delivery_date"] = pd.to_datetime(
    order_line["agreed_delivery_date"],
    dayfirst=True
)

order_line["actual_delivery_date"] = pd.to_datetime(
    order_line["actual_delivery_date"],
    dayfirst=True
)

aggregate["order_placement_date"] = pd.to_datetime(
    aggregate["order_placement_date"],
    dayfirst=True
)

In [20]:
print(order_line.dtypes)

print(aggregate.dtypes)

order_id                           str
order_placement_date    datetime64[us]
customer_id                      int64
product_id                       int64
order_qty                        int64
agreed_delivery_date    datetime64[us]
actual_delivery_date    datetime64[us]
delivery_qty                     int64
In Full                          int64
On Time                          int64
On Time In Full                  int64
dtype: object
order_id                           str
customer_id                      int64
order_placement_date    datetime64[us]
on_time                          int64
in_full                          int64
otif                             int64
dtype: object

In [21]:
print("Customers Shape :", customers.shape)
print("Products Shape :", products.shape)
print("Order Line Shape :", order_line.shape)
print("Aggregate Shape :", aggregate.shape)
print("Targets Shape :", targets.shape)

Customers Shape : (35, 4)
Products Shape : (18, 5)
Order Line Shape : (24195, 11)
Aggregate Shape : (13467, 6)
Targets Shape : (35, 4)