# 2. Data Exploration

## Objective

The purpose of this section is to explore the supply chain database and understand the size, structure, and distribution of the data before performing KPI analysis.

The analysis covers:

- Customer distribution
- Product distribution
- Order statistics
- Geographic distribution
- Currency distribution

In [41]:
import pandas as pd

In [42]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect("supply_chain.db")

print("✅ Connected to SQLite Database Successfully!")

✅ Connected to SQLite Database Successfully!

In [43]:
## view all tables in the database 
pd.read_sql("""
SELECT name
FROM sqlite_master
WHERE type='table';
""", conn)

                 name
0       dim_customers
1        dim_products
2  dim_targets_orders
3      fact_aggregate
4     fact_order_line

In [44]:
## Total Customers in the database 
pd.read_sql("""
SELECT
    COUNT(*) AS total_customers
FROM dim_customers;
""", conn)

   total_customers
0               35

In [45]:
## Customer Distribution by City
pd.read_sql("""
SELECT
    city,
    COUNT(*) AS total_customers
FROM dim_customers
GROUP BY city
ORDER BY total_customers DESC;
""", conn)

             city  total_customers
0        Vadodara               12
1       Ahmedabad               12
2  New Jersey, US               11

In [46]:
## Customer Distribution by Currency
pd.read_sql("""
SELECT
    currency,
    COUNT(*) AS total_customers
FROM dim_customers
GROUP BY currency;
""", conn)

  currency  total_customers
0      INR               24
1      USD               11

In [47]:
## Total Products
pd.read_sql("""
SELECT
    COUNT(*) AS total_products
FROM dim_products;
""", conn)

   total_products
0              18

In [48]:
## Products by Category
pd.read_sql("""
SELECT
    category,
    COUNT(*) AS total_products
FROM dim_products
GROUP BY category
ORDER BY total_products DESC;
""", conn)

    category  total_products
0      Dairy              12
1  beverages               3
2       Food               3

In [49]:
pd.read_sql("""
SELECT
    product_id,
    product_name,
    category
FROM dim_products
ORDER BY category, product_name;
""", conn)

    product_id     product_name   category
0     25891201    AM Butter 100      Dairy
1     25891202    AM Butter 250      Dairy
2     25891203    AM Butter 500      Dairy
3     25891402      AM Curd 100      Dairy
4     25891401      AM Curd 250      Dairy
5     25891403       AM Curd 50      Dairy
6     25891303      AM Ghee 100      Dairy
7     25891302      AM Ghee 150      Dairy
8     25891301      AM Ghee 250      Dairy
9     25891103      AM Milk 100      Dairy
10    25891102      AM Milk 250      Dairy
11    25891101      AM Milk 500      Dairy
12    25891503  AM Biscuits 250       Food
13    25891502  AM Biscuits 500       Food
14    25891501  AM Biscuits 750       Food
15    25891603       AM Tea 100  beverages
16    25891602       AM Tea 250  beverages
17    25891601       AM Tea 500  beverages

In [50]:
## Total Orders
pd.read_sql("""
SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM fact_aggregate;
""", conn)

   total_orders
0         13467

In [51]:
## Total Order Lines
pd.read_sql("""
SELECT
    COUNT(*) AS total_order_lines
FROM fact_order_line;
""", conn)

   total_order_lines
0              24195

In [52]:
## Preview Aggregate Table
pd.read_sql("""
SELECT *
FROM fact_aggregate
LIMIT 10;
""", conn)

      order_id  customer_id order_placement_date  on_time  in_full  otif
0  FMR32103503       789103           01-03-2025        1        0     0
1  FMR34103403       789103           01-03-2025        1        0     0
2  FMR32103602       789103           01-03-2025        1        0     0
3  FMR33103602       789103           01-03-2025        1        0     0
4  FMR33103401       789103           01-03-2025        1        0     0
5  FMR34903603       789903           01-03-2025        1        0     0
6  FMR32903403       789903           01-03-2025        1        0     0
7  FMR33903601       789903           01-03-2025        1        0     0
8  FMR32702601       789702           01-03-2025        1        0     0
9  FMR34702502       789702           01-03-2025        1        0     0

In [53]:
## Preview Order Line Table
pd.read_sql("""
SELECT *
FROM fact_order_line
LIMIT 10;
""", conn)

,order_id,order_placement_date,customer_id,product_id,order_qty,agreed_delivery_date,actual_delivery_date,delivery_qty,In Full,On Time,On Time In Full
0,FMR34203601,01-03-2025,789203,25891601,110,04-03-2025,04-03-2025,110,1,1,1
1,FMR32320302,01-03-2025,789320,25891203,347,02-03-2025,02-03-2025,347,1,1,1
2,FMR33320501,01-03-2025,789320,25891203,187,03-03-2025,03-03-2025,150,0,1,0
3,FMR34220601,01-03-2025,789220,25891203,235,04-03-2025,04-03-2025,235,1,1,1
4,FMR33703603,01-03-2025,789703,25891203,176,03-03-2025,03-03-2025,176,1,1,1
5,FMR33721603,01-03-2025,789721,25891203,345,03-03-2025,03-03-2025,345,1,1,1
6,FMR33420203,01-03-2025,789420,25891203,138,03-03-2025,06-03-2025,138,1,0,0
7,FMR34420402,01-03-2025,789420,25891203,381,04-03-2025,05-03-2025,381,1,0,0
8,FMR32403401,01-03-2025,789403,25891203,348,02-03-2025,02-03-2025,348,1,1,1
9,FMR34121203,01-03-2025,789121,25891203,480,04-03-2025,06-03-2025,480,1,0,0

In [54]:
## Check for Missing Customer Names
pd.read_sql("""
SELECT *
FROM dim_customers
WHERE customer_name IS NULL;
""", conn)

Empty DataFrame
Columns: [customer_id, customer_name, city, currency]
Index: []

In [55]:
## Check for missing Product Names 
pd.read_sql("""
SELECT *
FROM dim_products
WHERE product_name IS NULL;
""", conn)

Empty DataFrame
Columns: [product_name, product_id, category, price_INR, price_USD]
Index: []

In [56]:
## Count Orders by Customer
pd.read_sql("""
SELECT
    customer_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM fact_aggregate
GROUP BY customer_id
ORDER BY total_orders DESC;
""", conn)

    customer_id  total_orders
0        789521           518
1        789122           518
2        789121           511
3        789420           507
4        789522           500
5        789421           496
6        789422           487
7        789520           471
8        789221           373
9        789102           371
10       789720           366
11       789503           365
12       789301           364
13       789601           362
14       789101           361
15       789603           359
16       789702           358
17       789621           357
18       789622           354
19       789320           354
20       789402           353
21       789721           352
22       789903           349
23       789902           349
24       789321           347
25       789202           347
26       789401           342
27       789103           342
28       789220           340
29       789501           338
30       789703           337
31       789303           337
32       789203           334
33       789403           324
34       789201           324

In [57]:
## Count Products Ordered
pd.read_sql("""
SELECT
    product_id,
    COUNT(*) AS total_order_lines
FROM fact_order_line
GROUP BY product_id
ORDER BY total_order_lines DESC;
""", conn)

    product_id  total_order_lines
0     25891203               1409
1     25891503               1377
2     25891102               1374
3     25891502               1363
4     25891601               1361
5     25891301               1360
6     25891403               1356
7     25891501               1355
8     25891202               1352
9     25891602               1349
10    25891201               1333
11    25891101               1332
12    25891402               1326
13    25891302               1318
14    25891401               1317
15    25891303               1305
16    25891603               1304
17    25891103               1304

## Summary

The data exploration phase provided an overview of the supply chain database, including customer distribution, product catalog, order volume, and basic data quality checks.

These insights establish a strong foundation for calculating business KPIs and performing deeper customer, product, and delivery analysis in the following sections.

In [58]:
pd.read_sql("PRAGMA table_info(dim_products);", conn)

   cid          name     type  notnull dflt_value  pk
0    0  product_name     TEXT        0       None   0
1    1    product_id  INTEGER        0       None   0
2    2      category     TEXT        0       None   0
3    3     price_INR  INTEGER        0       None   0
4    4     price_USD     REAL        0       None   0

In [59]:
pd.read_sql("PRAGMA table_info(fact_aggregate);", conn)

   cid                  name     type  notnull dflt_value  pk
0    0              order_id     TEXT        0       None   0
1    1           customer_id  INTEGER        0       None   0
2    2  order_placement_date     TEXT        0       None   0
3    3               on_time  INTEGER        0       None   0
4    4               in_full  INTEGER        0       None   0
5    5                  otif  INTEGER        0       None   0

In [60]:
pd.read_sql("PRAGMA table_info(fact_order_line);", conn)

    cid                  name     type  notnull dflt_value  pk
0     0              order_id     TEXT        0       None   0
1     1  order_placement_date     TEXT        0       None   0
2     2           customer_id  INTEGER        0       None   0
3     3            product_id  INTEGER        0       None   0
4     4             order_qty  INTEGER        0       None   0
5     5  agreed_delivery_date     TEXT        0       None   0
6     6  actual_delivery_date     TEXT        0       None   0
7     7          delivery_qty  INTEGER        0       None   0
8     8               In Full  INTEGER        0       None   0
9     9               On Time  INTEGER        0       None   0
10   10       On Time In Full  INTEGER        0       None   0