# 3. Business KPIs

## Objective

Calculate key Supply Chain KPIs to evaluate order fulfillment performance and delivery efficiency.

In [3]:
import sqlite3
import pandas as pd

# Connect to the SQLite database
conn = sqlite3.connect("supply_chain.db")

print("✅ Connected to SQLite Database Successfully!")

✅ Connected to SQLite Database Successfully!

In [4]:
!pip install sqlalchemy

In [5]:
## KPI 1 - Total Orders
pd.read_sql("""
-- Business Question:
-- How many unique customer orders were placed?

SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM fact_aggregate;
""", conn)

   total_orders
0         13467

In [6]:
## KPI 2 – Total Order Lines
pd.read_sql("""
-- Business Question:
-- How many order lines were processed?

SELECT
    COUNT(*) AS total_order_lines
FROM fact_order_line;
""", conn)

   total_order_lines
0              24195

In [7]:
## KPI 3 – On-Time Delivery %
pd.read_sql("""
-- Business Question:
-- What percentage of order lines were delivered on time?

SELECT
    ROUND(AVG("On Time") * 100, 2) AS on_time_delivery_percentage
FROM fact_order_line;
""", conn)

   on_time_delivery_percentage
0                        71.21

In [8]:
## KPI 4 – In-Full Delivery %
pd.read_sql("""
-- Business Question:
-- What percentage of order lines were delivered in full?

SELECT
    ROUND(AVG("In Full") * 100, 2) AS in_full_delivery_percentage
FROM fact_order_line;
""", conn)

   in_full_delivery_percentage
0                        65.93

In [9]:
## KPI 5 – OTIF %
pd.read_sql("""
-- Business Question:
-- What percentage of order lines were delivered On Time In Full?

SELECT
    ROUND(AVG("On Time In Full") * 100, 2) AS otif_percentage
FROM fact_order_line;
""", conn)

   otif_percentage
0            47.84

In [10]:
## KPI 6 – Line Fill Rate = (Number of order lines delivered in full ÷ Total order lines) × 100
pd.read_sql("""
SELECT
    ROUND(
        SUM("In Full") * 100.0 / COUNT(*),
        2
    ) AS line_fill_rate
FROM fact_order_line;
""", conn)

   line_fill_rate
0           65.93

In [11]:
## KPI 7 – Volume Fill Rate
## (Total Delivered Quantity ÷ Total Ordered Quantity) × 100
pd.read_sql("""
SELECT
    ROUND(
        SUM(delivery_qty) * 100.0 /
        SUM(order_qty),
        2
    ) AS volume_fill_rate
FROM fact_order_line;
""", conn)

   volume_fill_rate
0              96.6