# 4. Customer Analysis

## Objective

Analyze customer purchasing behavior and service performance.

This section identifies:

- Top customers by order value
- Customer-wise revenue
- OTIF performance
- On-Time Delivery %
- In-Full Delivery %

In [1]:
import pandas as pd 
import sqlite3
# Connect to the SQLite database
conn = sqlite3.connect("../data/supply_chain.db")

print("✅ Connected to SQLite Database Successfully!")

✅ Connected to SQLite Database Successfully!

In [2]:
## Bottom 5 Customers by Revenue
pd.read_sql("""
SELECT

c.customer_name,

c.city,

SUM(
f.delivery_qty*p.price_INR
) AS revenue

FROM fact_order_line f

JOIN dim_customers c
ON f.customer_id=c.customer_id

JOIN dim_products p
ON f.product_id=p.product_id

GROUP BY
c.customer_name,
c.city

ORDER BY revenue ASC

LIMIT 5;

""", conn)

      customer_name            city   revenue
0        Lotus Mart       Ahmedabad  15182637
1    Fairway Market  New Jersey, US  15272733
2         Rel Fresh        Vadodara  15520106
3  Acclaimed Stores        Vadodara  15574423
4      Sorefoz Mart       Ahmedabad  15687650

In [3]:
## Top five customers by order value
pd.read_sql("""
SELECT
    c.customer_id,
    c.customer_name,
    c.city,

    ROUND(
        SUM(f.delivery_qty * p.price_INR),
        2
    ) AS order_value

FROM fact_order_line AS f

JOIN dim_customers AS c
ON f.customer_id = c.customer_id

JOIN dim_products AS p
ON f.product_id = p.product_id

GROUP BY
    c.customer_id,
    c.customer_name,
    c.city

ORDER BY order_value DESC

LIMIT 5;
""", conn)

   customer_id       customer_name            city  order_value
0       789402         Propel Mart       Ahmedabad   18064754.0
1       789902          Elite Mart       Ahmedabad   17745012.0
2       789301            Foodtown  New Jersey, US   17738559.0
3       789320  Whole Foods Market  New Jersey, US   17683051.0
4       789102        Vijay Stores       Ahmedabad   17657794.0

In [4]:
import pandas as pd
pd.read_sql("""
SELECT COUNT(*)
FROM dim_customers;
""",conn)

   COUNT(*)
0        35

In [5]:
pd.read_sql("""
SELECT
    c.customer_id,
    c.customer_name,
    c.city,
    SUM(f.delivery_qty * p.price_INR) AS total_revenue
FROM fact_order_line f
JOIN dim_customers c
    ON f.customer_id = c.customer_id
JOIN dim_products p
    ON f.product_id = p.product_id
GROUP BY
    c.customer_id,
    c.customer_name,
    c.city
ORDER BY total_revenue DESC;
""",conn)

    customer_id       customer_name            city  total_revenue
0        789402         Propel Mart       Ahmedabad       18064754
1        789902          Elite Mart       Ahmedabad       17745012
2        789301            Foodtown  New Jersey, US       17738559
3        789320  Whole Foods Market  New Jersey, US       17683051
4        789102        Vijay Stores       Ahmedabad       17657794
5        789521    Acclaimed Stores       Ahmedabad       17639371
6        789503       Viveks Stores        Vadodara       17540834
7        789603         Info Stores        Vadodara       17458607
8        789420                Lidl  New Jersey, US       17265594
9        789220            ShopRite  New Jersey, US       17139724
10       789401             Wegmans  New Jersey, US       17115122
11       789720      Colonial Farms  New Jersey, US       16977328
12       789621         Expert Mart       Ahmedabad       16909962
13       789101    Costco Wholesale  New Jersey, US       16902279
14       789622         Expert Mart        Vadodara       16884932
15       789403         Propel Mart        Vadodara       16789765
16       789721        Logic Stores       Ahmedabad       16745389
17       789202           Rel Fresh       Ahmedabad       16705112
18       789201           Rel Fresh  New Jersey, US       16687838
19       789103        Vijay Stores        Vadodara       16633521
20       789321      Chiptec Stores       Ahmedabad       16617561
21       789422          Lotus Mart        Vadodara       16544368
22       789601          Price Rite  New Jersey, US       16391369
23       789703        Sorefoz Mart        Vadodara       16334762
24       789303   Expression Stores        Vadodara       16331451
25       789121            Coolblue       Ahmedabad       16299938
26       789501         Best Market  New Jersey, US       16094889
27       789221        Atlas Stores       Ahmedabad       16057771
28       789903          Elite Mart        Vadodara       16030421
29       789122            Coolblue        Vadodara       15740009
30       789702        Sorefoz Mart       Ahmedabad       15687650
31       789522    Acclaimed Stores        Vadodara       15574423
32       789203           Rel Fresh        Vadodara       15520106
33       789520      Fairway Market  New Jersey, US       15272733
34       789421          Lotus Mart       Ahmedabad       15182637

In [6]:
pd.read_sql("""
SELECT
    customer_name,
    COUNT(*) AS cnt
FROM dim_customers
GROUP BY customer_name
HAVING COUNT(*) > 1;
""",conn)

      customer_name  cnt
0  Acclaimed Stores    2
1          Coolblue    2
2        Elite Mart    2
3       Expert Mart    2
4        Lotus Mart    2
5       Propel Mart    2
6         Rel Fresh    3
7      Sorefoz Mart    2
8      Vijay Stores    2

In [7]:
## Top 5 Customers with OTIF %
pd.read_sql("""
SELECT

    c.customer_id,

    c.customer_name,

    c.city,

    ROUND(
        SUM(f.delivery_qty * p.price_INR),
        2
    ) AS order_value,

    ROUND(
        AVG(f."On Time In Full") * 100,
        2
    ) AS otif_percentage

FROM fact_order_line f

JOIN dim_customers c
ON f.customer_id = c.customer_id

JOIN dim_products p
ON f.product_id = p.product_id

GROUP BY

    c.customer_id,

    c.customer_name,

    c.city

ORDER BY order_value DESC

LIMIT 5;
""", conn)

,customer_id,customer_name,city,order_value,otif_percentage
0,789402,Propel Mart,Ahmedabad,18064754.0,64.64
1,789902,Elite Mart,Ahmedabad,17745012.0,66.25
2,789301,Foodtown,"New Jersey, US",17738559.0,57.45
3,789320,Whole Foods Market,"New Jersey, US",17683051.0,62.01
4,789102,Vijay Stores,Ahmedabad,17657794.0,59.86

In [8]:
## Top 5 Customers with OTIF, OT and IF
pd.read_sql("""
SELECT

    c.customer_id,

    c.customer_name,

    c.city,

    ROUND(
        SUM(f.delivery_qty * p.price_INR),
        2
    ) AS order_value,

    ROUND(
        AVG(f."On Time In Full") * 100,
        2
    ) AS otif_percentage,

    ROUND(
        AVG(f."On Time") * 100,
        2
    ) AS on_time_percentage,

    ROUND(
        AVG(f."In Full") * 100,
        2
    ) AS in_full_percentage

FROM fact_order_line f

JOIN dim_customers c
ON f.customer_id = c.customer_id

JOIN dim_products p
ON f.product_id = p.product_id

GROUP BY

    c.customer_id,

    c.customer_name,

    c.city

ORDER BY order_value DESC

LIMIT 5;
""", conn)

,customer_id,customer_name,city,order_value,otif_percentage,on_time_percentage,in_full_percentage
0,789402,Propel Mart,Ahmedabad,18064754.0,64.64,86.28,74.26
1,789902,Elite Mart,Ahmedabad,17745012.0,66.25,86.41,76.33
2,789301,Foodtown,"New Jersey, US",17738559.0,57.45,81.98,72.49
3,789320,Whole Foods Market,"New Jersey, US",17683051.0,62.01,82.63,75.00
4,789102,Vijay Stores,Ahmedabad,17657794.0,59.86,82.45,73.61